### ISSUE TITLE
include function has been depreciated 

### ISSUE THREAD

**Issue by korilium** [GenieFramework/StippleDemos#14]
When I followed the readme file inside of BasicExamples, there is one step where you want to load in your code using the include function but I get the following error
```julia 
┌ Warning: This method has been deprecated and will be removed soon. Please use `init(m::Type{M}, kwargs...)` instead.
└ @ Stipple C:\Users\ignac\.julia\packages\Stipple\qLkpM\src\Stipple.jl:788
ERROR: LoadError: UndefVarError: setfield not defined
Stacktrace:
 [1] setchannel(m::FormComponent, value::String)
   @ Stipple C:\Users\ignac\.julia\packages\Stipple\qLkpM\src\Stipple.jl:255
 [2] init(m::Type{FormComponent}; vue_app_name::String, endpoint::String, channel::Nothing, debounce::Int64, transport::Module, parse_errors::Bool, core_theme::Bool)
   @ Stipple C:\Users\ignac\.julia\packages\Stipple\qLkpM\src\Stipple.jl:735
 [3] init(m::Type{FormComponent})
   @ Stipple C:\Users\ignac\.julia\packages\Stipple\qLkpM\src\Stipple.jl:725
 [4] init(m::FormComponent; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})      
   @ Stipple C:\Users\ignac\.julia\packages\Stipple\qLkpM\src\Stipple.jl:789
 [5] init(m::FormComponent)
   @ Stipple C:\Users\ignac\.julia\packages\Stipple\qLkpM\src\Stipple.jl:788
 [6] top-level scope
   @ c:\Users\ignac\Documents\julia_learn\StippleDemos\BasicExamples\Form.jl:18
in expression starting at c:\Users\ignac\Documents\julia_learn\StippleDemos\BasicExamples\Form.jl:18
``` 

How should you use init or is there another way to load the file? I tried 
```julia
 init("Form.jl")
``` 

but to no avail. 

I think it has something to do with 

```julia
 <pkg> instantiate
``` 
Because it gives me no respons

**Comment by hhaensel** [comment]
I think you are mixing up things. If you want to include a file in Julia, you do `include("Form.jl")` if you want to initialise a model of type `Form`, then you initialise it by `model = init(Form)`.
If this doesn't help you, please specify the code you are executing.

**Comment by hhaensel** [comment]
I just noticed, the warning comes from the fact that you called init(Form()) rather than init(Form) (The syntax has changed recently).
The error is due to a typo in the latest Stipple version that has been fixed 5 days ago. So please for the time being be sure to use the master branch
```julia
]add Stippple#master
```

**Comment by korilium** [comment]
Okay so I removed the current Stipple version with 

```Julia 
] rm Stipple
```
and then add the new Stipple version following your example 

```Julia 
] add Stipple#master 
``` 
but I get the following problem: 
```Julia 
(BasicExamples) pkg> add Stipple#master
    Updating git-repo `https://github.com/GenieFramework/Stipple.jl.git`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package StippleCharts [30ddb3f0]:
 StippleCharts [30ddb3f0] log:
 ├─possible versions are: 0.1.0-0.16.0 or uninstalled
 ├─restricted to versions 0.16 by an explicit requirement, leaving only versions 0.16.0
 └─restricted by compatibility requirements with Stipple [4acbeb90] to versions: uninstalled — no versions left
   └─Stipple [4acbeb90] log:
     ├─possible versions are: 0.20.3 or uninstalled
     └─Stipple [4acbeb90] is fixed to version 0.20.3
```

If I check the status of the Stipple package, I get this 

```julia 
(BasicExamples) pkg> status Stipple
  No Matches in `C:\Users\ignac\Documents\julia_learn\StippleDemos\BasicExamples\Project.toml`
```


Hopefully, someone can help me with this regard

For clarification I try to run the demo as is described in this <a href= "https://github.com/GenieFramework/StippleDemos/blob/master/BasicExamples/README.md" > file </a> .

**Comment by hhaensel** [comment]
Try bringing all Stipple packages to master

**Comment by korilium** [comment]
when I set all Stipple packages to master the package version problem is resolved. 

 But the include function still does not work and gives me the same error as mentioned above. 

Again this is what I try to do: 

```Julia
$ cd path-to-BasicExamples
$ Julia --project
julia> #enter package mode with ]
(@v1.x) pkg> activate .
(@v1.x) pkg> instantiate
(@v1.x) pkg> #exit package mode with <backspace key>
julia> include("Form.jl")
julia> up(rand((8000:9000)), open_browser=true)  # should open your default browser and fire up Genie server at port between `8000:9000`
julia> down() # stop the running async instance of Genie Server
````

And it fails when I try to run: 

```Julia 
julia> include("Form.jl")
```

I believe the error message (which states that include is depreciated and I need to use init) does not convey the right answer as everything runs well when I try to run the GermanCredit example which also starts with the same code : 

```Julia
julia> julia --project
julia> #enter package mode with ]
(@v1.x) pkg> activate .
(@v1.x) pkg> instantiate
(@v1.x) pkg> #exit package mode with <backspace key>
julia> include("GermanCredits.jl")
julia> up(rand((8000:9000)), open_browser=true)  # should open your default browser and fire up Genie server at port between `8000:9000`
julia> down() # stop the running async instance of Genie Server
```
Hopefully, someone can figure out what I am missing. 

Thanks in advance to have a look at it.

**Comment by hhaensel** [comment]
For me it works if I'm on master of Stipple, StippleUI and StippledDemos

**Comment by essenciary** [comment]
The warning has nothing to do with this (also it's a warning, not an error).
The `setfield` exception is due to a bug in the registered version of Stipple. If the master gives you the same error, you're probably not on master. Can you provide the output for `pkg> st` to make sure? 
I'll tag a new release for Stipple today though, so no worries, you can try again a bit later and it should work.

**Comment by korilium** [comment]
Thanks much appreciated!
